[project]
name = "tiny-onn"
version = "0.1.0"
authors = [{ name = "Rui.Lin", email = "Lin.Rui.ipwt@proton.me" }]
description = ""
readme = "README.md"
requires-python = ">=3.12"
license = { text = "AGPL-3.0-or-later" }
dependencies = [
  "matplotlib",
  "mypy",
  "packaging>=25.0",
  "pytest>=8.4.1",
  "ruff>=0.12.1",
  "tensorboard>=2.14.0",
  "tqdm>=4.67.1",
]

[project.urls]
"Homepage" = "https://github.com/dmf-archive/Tiny-ONN"
"Bug Tracker" = "https://github.com/dmf-archive/Tiny-ONN/issues"

[dependency-groups]
dev = [
  "mypy>=1.14.1",
  "torch==2.7.1+cu128",
  "torchvision",
  "torchaudio",
  "omegaid[cuda-12x]>=0.1.3",
]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
ignore_missing_imports = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.ruff.lint]
select = ["I", "F", "B", "NPY"]
