data:
  mode: "local_json"
  train_path: "data/dummy_chat_data.jsonl"

model:
  vocab_size: 50257
  num_hidden_layers: 2
  num_attention_heads: 4
  hidden_size: 32
  head_dim: 8
  intermediate_size: 32
  moe_intermediate_size: 32
  num_experts_per_layer: 32
  selection_block_size: 16
  max_selected_blocks: 16
  w_ce: 1.0
  w_kl: 0.5
  w_entropy: 1.0
  w_sparse: 1.0
  pi_alpha: 1.0
  pi_gamma: 0.5

train:
  learning_rate: 1e-4
  num_epochs: 30
  log_interval: 10
  surprise_threshold_sigma: 2.0

observer:
  output_dir: "output/E2E_test_train"
  pi_gamma: 0.5
  pi_alpha: 1.0